### ISSUE TITLE
Retries are not done for collections/items/requests/logs iterators.

### ISSUE THREAD

**Issue by hermit-crab** [scrapinghub/python-scrapinghub#126]
Good day. We have a project that makes extensive use of the API and at certain times "429 Too many requests for user" occur and are raised with no indication of any retries, exponential or otherwise, taking place. In fact it seems no HTTP errors are retried for resource iterators whatsoever:
https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/hubstorage/resourcetype.py#L134-L143
Although I see other places do handle such:
https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/hubstorage/client.py#L20-L37
Is this by design?

UPD:
So at this point: https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/hubstorage/client.py#L113-L116
the iterator request executed as is without retrier wrapping as it deemed not idempotent. At a later point here: https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/hubstorage/resourcetype.py#L134-L143 it is not handled at all (`scrapinghub.client.exceptions.ScrapinghubAPIError('Too many requests for user')` in our case).

**Comment by vshlapakov** [comment]
Hey, thanks for the report! I believe your observations are correct, and the requests sent by the resource iterators are considered to be not idempotent, thus not retried on any of the listed exceptions. It's not by design, this is something that would be nice to fix.

Worth to add that the issue affects only iterating over/listing a collection elements, and doesn't affect items/requests/logs. (While we call the origin `iter_values` [method](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/client/collections.py#L222) for collections, it's origin `list` [method](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/client/proxy.py#L83) for items/requests/logs which uses `apiget` [method](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/hubstorage/resourcetype.py#L220) underneath with setting `is_idempotent=True` [by default](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/hubstorage/resourcetype.py#L86))

**Comment by hermit-crab** [comment]
Hi @vshlapakov, thank you for the reply.
> doesn't affect items/requests/logs

I don't believe that's the case. `Items` object MRO is:
```
<class 'scrapinghub.client.items.Items'>
<class 'scrapinghub.client.proxy._DownloadableProxyMixin'>
<class 'scrapinghub.client.proxy._ItemsResourceProxy'>
<class 'scrapinghub.client.proxy._Proxy'>
<class 'object'>
```
It calls [_DownloadableProxyMixin.iter()](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/client/proxy.py#L104) (-> `_origin.iter_values()` -> `_origin.iter_json/msgpack()`) and not [_ItemsResourceProxy.iter()](https://github.com/scrapinghub/python-scrapinghub/blob/master/scrapinghub/client/proxy.py#L74). Same for logs and requests.

**Comment by vshlapakov** [comment]
My bad, I had an old version of the library installed locally, there was a different MRO before.
A PR is highly welcome if you have time.

**Comment by vshlapakov** [comment]
This should be covered now, thanks again for the thorough investigation and the clean patch :raised_hands:
