### ISSUE TITLE
requests.exceptions.ReadTimeout on `jobq.list`

### ISSUE THREAD

**Issue by shivam6294** [scrapinghub/python-scrapinghub#68]
So, for one of the projects I'm working on - I'm writing an automation script that decides how many and which jobs to send the scrapinghub.

To do precisely that, I need to get the number of pending or running jobs from scrapinghub. So, I decided to keep this simple and this was the code I came up with (using the `jobq` api)- 

```
    def get_num_pending_or_running_jobs():
        num_pending_jobs = len(list(project.jobq.list(state='pending')))
        num_running_jobs = len(list(project.jobq.list(state='running')))
        return num_pending_jobs + num_running_jobs
```

This resulted in a `ReadTimeout` after about a couple hours of running:- 
```
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='storage.scrapinghub.com', port=443): Read timed out. (read timeout=60.0). Can't afford this as getting the list of pending or running jobs is absolutely necessary for the project I'm working on.
```

Does anyone know why this is happening? Does this happen very often?

Any help would be appreciated

**Comment by vshlapakov** [comment]
Apologises for the so late reply. It's most likely not actual, but for future reads such errors are usually temporary and like `requests` [states](https://github.com/requests/requests/blob/v2.18.4/requests/exceptions.py#L60) - basically mean that `the server did not send any data in the allotted amount of time`. It should be unfrequent, but still can cappen from time to time due to network glitches or outages.

From our side this could be improved by adding retry settings to the client: for example we could [setup retrying logic](https://stackoverflow.com/questions/15431044/can-i-set-max-retries-for-requests-request) via a custom `HTTPAdapter`, it's something that looks very useful to me.

**Comment by vshlapakov** [comment]
I'm closing this issue for now, let me know if you have other questions or ping Scrapinghub support.
